import { PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import AppProvider from '@/common/providers/AppProvider';
import GlobalStyleProvider from '@/common/providers/GlobalStyleProvider';
import 'antd-css-utilities/utility.min.css';
import Head from 'next/head';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang='en'>
      <Script src='https://www.gstatic.com/firebasejs/ui/6.0.1/firebase-ui-auth.js'></Script>
      <Head>
        <link
          type='text/css'
          rel='stylesheet'
          href='https://www.gstatic.com/firebasejs/ui/6.0.1/firebase-ui-auth.css'
        />
      </Head>
      <body className={inter.className}>
        <AppProvider>
          <GlobalStyleProvider>{children}</GlobalStyleProvider>
        </AppProvider>
      </body>
    </html>
  );
}
